# Generated by Django 4.1.7 on 2023-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_category_inventory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Category',
            field=models.CharField(choices=[('category', 'Quote'), ('category', 'Approved Orders')], max_length=20, null=True),
        ),
    ]
