# Generated by Django 4.1.7 on 2023-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_inventory_options_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory System'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order System'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='Price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
