# Generated by Django 4.1.7 on 2023-03-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_inventory_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
