# Generated by Django 4.1.7 on 2023-03-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Inventory',
            new_name='Product',
        ),
    ]
