# Generated by Django 4.1.7 on 2023-03-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_inventory_order_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
    ]
